name: Deposit with Crossref
description: Deposit with Crossref API call
inputs:
  crossref_filepath:
    description: The complete filepath of the Crossref XML file
    required: true
  crossref_username:
    description: Crossref username doing the deposit
    required: true
  crossref_password:
    description: Crossref password
    required: true
  crossref_mode:
    description: Use test or production crossref calls
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
        cache-version: deposit-with-crossref
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Deposit with Crossref
      id: deposit_crossref
      shell: bash
      env:
        CROSSREF_FILEPATH: ${{ inputs.crossref_filepath }}
        CROSSREF_USERNAME: ${{ inputs.crossref_username }}
        CROSSREF_PASSWORD: ${{ inputs.crossref_password }}
        CROSSREF_MODE: ${{ inputs.crossref_mode }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/deposit_with_crossref.rb
branding:
  icon: upload-cloud
  color: green
